from sqlalchemy import Column, Integer, String, Date, Text, Numeric, SmallInteger, Float, DateTime
from app.core.database import Base


class TableroProduccion(Base):
    __tablename__ = "tablero_produccion"

    id = Column(Integer, primary_key=True)
    UN = Column(String(50), nullable=False, default="")
    operacion = Column(String(50), nullable=False, default="")
    fecha = Column(Date, nullable=True)
    equipo = Column(String(50), nullable=False, default="")
    operador = Column(String(50), nullable=False, default="")
    hr_inicio = Column(Numeric(12, 2), nullable=False, default=0)
    hr_fin = Column(Numeric(12, 2), nullable=False, default=0)
    combustible = Column(Integer, nullable=False, default=0)
    aceite_cadena = Column(Integer, nullable=False, default=0)
    acta = Column(String(10), nullable=False, default="0")
    rodal = Column(String(10), nullable=False, default="0")
    m3 = Column(Integer, nullable=False, default=0)
    carros = Column(Integer, nullable=False, default=0)
    tn_despachadas = Column(Numeric(12, 2), nullable=False, default=0)
    has = Column(Numeric(12, 2), nullable=False, default=0)
    produccion = Column(Numeric(12, 2), nullable=False, default=0)
    unitario = Column(Numeric(12, 2), nullable=False, default=0)
    unidad_produccion = Column(String(20), nullable=False, default="0")
    dist_tosquera = Column(Integer, nullable=False, default=0)
    mtrs_recorridos = Column(Integer, nullable=False, default=0)
    plantas = Column(Integer, nullable=False, default=0)
    viaje_tosca = Column(Integer, nullable=False, default=0)
    hrs_no_op = Column(Integer, nullable=False, default=0)
    motivo_no_op = Column(String(150), nullable=False, default="0")
    observaciones = Column(String(150), nullable=False, default="0")
    stock_abc = Column(Integer, nullable=False, default=0)
    aceite_hidraulico = Column(Integer, nullable=False, default=0)
    aceite_motor = Column(Integer, nullable=False, default=0)
    aceite_embrague = Column(Integer, nullable=False, default=0)
    aceite_transmision = Column(Integer, nullable=False, default=0)
    nro_parte = Column(Integer, nullable=False, default=0)
    predio = Column(String(50), nullable=False, default="0")
    cod_operador = Column(Integer, nullable=False, default=1)
    cod_equipo = Column(Integer, nullable=False, default=1)
    tarifa = Column(Numeric(12, 2), nullable=False, default=0)
    fijo = Column(Numeric(12, 2), nullable=False, default=0)
    km_carreteo = Column(Numeric(12, 2), nullable=False, default=0)
    km_perfilado = Column(Numeric(12, 2), nullable=False, default=0)
    hr_disposicion = Column(Numeric(12, 2), nullable=False, default=0)
    km_camioneta = Column(Integer, nullable=False, default=0)
    servicio_tercero = Column(SmallInteger, nullable=False, default=0)
    detalle_servicio = Column(String(50), nullable=False, default="")
    _uuid = Column(String(36), nullable=False, default="")
    form_uuid = Column(String(36), nullable=False, default="")
    remito = Column(String(12), nullable=False, default="")
    remito2 = Column(String(12), nullable=False, default="")
    remito3 = Column(String(12), nullable=False, default="")
    remito_bitren = Column(String(12), nullable=False, default="")
    cambio_cuchilla = Column(Integer, nullable=False, default=0)
    lugar_carga = Column(Integer, nullable=False, default=0)
    usuario = Column(String(50), nullable=True)
    cliente_camion = Column(String(50), nullable=True)
    origen_camion = Column(String(50), nullable=True)
    destino_camion = Column(String(50), nullable=True)
    fecha_hora = Column(DateTime, nullable=True)
    tarifa_empresa = Column(Float, nullable=False, default=0)
    origen_destino_id = Column(Integer, nullable=False, default=0)
    cod_un = Column(Integer, nullable=True)
    tabla = Column(String(50), nullable=True)
    codigo_tabla = Column(Integer, nullable=False, default=0)
    espada = Column(SmallInteger, nullable=True)
    puntera = Column(SmallInteger, nullable=True)
    cadena = Column(SmallInteger, nullable=True)
    pinon = Column(SmallInteger, nullable=True)
    cantidad_cadenas = Column(Integer, nullable=True, default=0)
    giro_pinon = Column(SmallInteger, nullable=True)
    origen = Column(String(80), nullable=True)
    modificado = Column(SmallInteger, nullable=False, default=0)
    hora_inicio_viaje = Column(String(8), nullable=True)
    hora_fin_viaje = Column(String(8), nullable=True)
    remito_proveedor = Column(String(20), nullable=True)
    remito_fgpy = Column(String(20), nullable=True)
    nombre_chofer = Column(String(100), nullable=True)
    parcela = Column(String(50), nullable=True)
    bruto_destino = Column(Float, nullable=False, default=0)
    tara_destino = Column(Float, nullable=False, default=0)
    neto_origen = Column(Float, nullable=False, default=0)
    neto_destino = Column(Float, nullable=False, default=0)
    proveedor_id = Column(Integer, nullable=True)
